### ISSUE TITLE
i am facing the issue while building over ios

### ISSUE THREAD

**Issue by Fredrik1234** [ReyHaynes/react-redux-web-native#1]
![screen shot 2018-05-04 at 12 27 25 pm](https://user-images.githubusercontent.com/19411725/39616808-b03e0e1a-4f96-11e8-83fd-cdab2926d2f6.png)
![screen shot 2018-05-04 at 12 13 29 pm](https://user-images.githubusercontent.com/19411725/39616422-c6a38a56-4f94-11e8-97ea-1515784bcf8f.png)

**Comment by Fredrik1234** [comment]
it works on web perfectly but when running command for build it for IOS above given issue occurs

**Comment by Fredrik1234** [comment]
app loads successfully til splash screen after that above error comes in simulator

**Comment by ReyHaynes** [comment]
@Fredrik1234 A common solution for this is to uninstall/reinstall or update `watchman`
```bash
## Uninstall Watchman
npm r -g watchman

## Install Watchman via NPM
npm i -g watchman

## Install Watchman via Homebrew
brew install watchman
```
